config/routes.rb
InteriorC::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  def draw_routes
    root 'home#index'

    resources :designers, only: [:new, :create, :update]

    resources :sessions, only: [] do
      collection do
        get 'logout'
        get 'designer_login'
        get 'client_login'
        post 'client_authenticate'
        get 'client_fb_authenticate'
        post 'authenticate'
        match 'designer_retry_password', via: [:post, :get]
        match 'client_retry_password', via: [:post, :get]
      end
    end

    get 'terms_of_service', to: 'home#terms_of_service'
    get 'faq', to: 'home#faq'
    get 'sign_up_beta', to: 'home#sign_up_beta'
    get 'how_it_works', to: 'home#how_it_works'
    get 'about_us', to: 'home#about_us'

    resources :contest_requests, only: [:show, :create] do
      resources :comments, controller: :concept_board_comments, only: [:create, :update, :destroy]
      member do
        get 'save_lookbook'
        post 'answer'
        post 'approve_fulfillment'
        get 'download'
      end
    end

    resources :contests, only: [:show, :update] do
      member do
        get 'option'
        get 'show', as: 'show'
        get 'brief', to: 'clients#brief', as: 'brief'
        get 'download_all_images_url'
        get 'design_brief'
        post 'save_design_brief'
        get 'design_style'
        post 'save_design_style'
        get 'design_space'
        post 'save_design_space'
        get 'preview'
        post 'save_preview'
        get 'image_items'
        resources :feedback,
                  controller: 'reviewer_feedbacks',
                  as: 'reviewer_feedbacks',
                  only: [:create] do

          collection do
            get '', to: 'reviewer_feedbacks#show', as: 'show'
          end
        end
      end

      collection do
        get 'design_brief'
        post 'save_design_brief'
        get 'design_style'
        post 'save_design_style'
        get 'design_space'
        post 'save_design_space'
        get 'preview'
        post 'save_preview'
        post 'upload'
        get 'invite_designers'
        get 'account_creation'
        get 'payment_details'
        get 'payment_summary'
        put 'save_intake_form'
      end

      resource :time_tracker do
        get '/', to: 'time_tracker#designer_view', as: 'designer_center'
        post 'suggest_hours', to: 'time_tracker#suggest_hours', as: 'suggest_hours'
        resources :designer_activities, only: [:create] do
          resources :comments, only: [:create], controller: 'designer_activity_comments'

          member do
            patch 'read', to: 'designer_activities#read'
          end
        end
        resources :attachments, only: [:create], controller: 'time_tracker_attachments'
      end
    end

    resources :images, only: [] do
      collection do
        get 'ready', to: 'images#ready'
        post 'sign', to: 'images#sign'
        post 'on_uploaded', to: 'images#on_uploaded'
      end
    end

    resources :clients, only: [:create, :update] do
      collection do
        get 'validate_card'
        post 'sign_up_with_facebook'
        post 'sign_up_with_email'
        post 'ssl_sign_up_with_email'
        get 'unsubscribe/:signature', to: 'clients#unsubscribe', as: 'unsubscribe'
      end
    end

    scope '/client_center' do
      resources :entries, only: [:index, :show], controller: 'contests', as: 'client_center_entries' do
        member do
          get 'time_tracker', to: 'time_tracker#client_view', as: 'time_tracker'
          post 'time_tracker/initialize_purchase', to: 'time_tracker#initialize_purchase', as: 'time_tracker_initialize_purchase'
          post 'time_tracker/confirm_purchase', to: 'time_tracker#confirm_purchase', as: 'time_tracker_confirm_purchase'
        end
      end
      get '', to: 'clients#client_center', as: 'client_center'
      get 'concept_boards_page', to: 'clients#concept_boards_page', as: 'client_center_concept_boards_page'
      get 'profile', to: 'clients#profile', as: 'client_center_profile'
      get 'pictures_dimension', to: 'clients#pictures_dimension', as: 'client_center_pictures_dimension'
    end

    resources :designers, only: [:create, :update]

    scope '/designer_center' do
      get '', to: 'designer_center#designer_center', as: 'designer_center'
      get 'updates', to: 'designer_center#updates', as: 'designer_center_updates'
      get 'training', to: 'designer_center#training', as: 'designer_center_training'
      resources :contests,
                controller: 'designer_center_contests',
                as: 'designer_center_contest',
                only: [:show, :index] do
        resources :comments, controller: :concept_board_comments, only: [:create]
        collection do
          get 'index'
        end
      end
      resources :responses,
                controller: 'designer_center_requests',
                as: 'designer_center_response',
                only: [:new, :create, :show, :index, :update, :edit] do
        member do
          get 'preview', as: 'preview'
          patch 'publish', as: 'publish'
        end

        resources :lookbook_details, only: [:create, :destroy]
      end
      resource :portfolio, only: [:edit, :update]
    end

    resources :designer_invitations, only: [:create]
    resources :contest_notes, only: [:create]
    resources :reviewer_invitations, only: [:create]
    resources :beta_subscribers, only: [:create]
    resources :image_items, only: [:create, :update, :new, :edit, :destroy] do
      member do
        patch 'mark', to: 'image_items#mark', as: 'mark'
      end
      collection do
        get 'default', to: 'image_items#default', as: 'default'
      end
    end
    resource :designs do
      get '/:token', to: 'contest_requests#design', as: 'public'
    end
    resources :notifications, only: [:show] do
      collection do
        get '/comments/:id', to: 'notifications#show_comment', as: 'comment'
      end
    end

    resources :promocodes, only: [] do
      collection do
        get '', to: 'promocodes#apply', as: 'apply'
      end
    end

    resources :lookbook_details, only: [] do
      collection do
        get '/preview', to: 'lookbook_details#preview', as: 'preview'
        delete '/remove_preview', to: 'lookbook_details#remove_preview', as: 'remove_preview'
      end
    end

    resources :final_notes,
              controller: 'final_notes',
              as: 'final_note',
              only: [:create]

    resources :credit_cards, only: [:create, :edit, :update, :destroy] do
      member do
        patch 'set_as_primary'
      end
    end

    resources :client_payments, only: [:create]

    get '/coming_soon', to: 'home#coming_soon', as: 'coming_soon'
    get '/privacy_policy', to: 'home#privacy_policy', as: 'privacy_policy'
    get '/designer_submission', to: 'home#designer_submission', as: 'designer_submission'
    get '/justines_story', to: 'blog#justines_story', as: 'justines_story'

    scope '/blog' do
      get '/', to: 'blog#blog_root', as: 'blog_root'
      get '/designers', to: 'blog#designers_blog_root', as: 'designers_blog_root'
      get '/designers/:blog_page_path',
          to: 'blog#designers_blog_page',
          as: 'designers_blog_page',
          constraints: { blog_page_path: /.*/ }
      post '/designers/:blog_page_path',
           to: 'blog#designers_blog_page_post',
           as: 'designers_blog_page_post',
           constraints: { blog_page_path: /.*/ }
      get '/:blog_page_path',
          to: 'blog#blog_page',
          as: 'blog_page',
          constraints: { blog_page_path: /.*/ }
      post '/:blog_page_path',
           to: 'blog#blog_page_post',
           as: 'blog_page_post',
           constraints: { blog_page_path: /.*/ }
    end

    resources :outbound_emails, :controller => 'email_webhooks', :only => [:show, :create]
    get '/outbound_emails', to: 'email_webhooks#verify', via: :head

    resources :giftcard_payments, controller: 'giftcard_payments', only: [:create, :index]

    get '/sfar', to: 'realtor_contacts#sfar', as: 'sfar'
    get '/giftcards', to: 'giftcard_payments#new', as: 'new_giftcard_payment'

    resources :realtor_contacts, only: [:create]

    get 'sitemap.xml' => 'sitemaps#sitemap_index', format: :xml, as: :sitemap_index
    get 'sitemap_index.xml' => 'sitemaps#sitemap_index', format: :xml
    get 'sitemaps/:sitemap_file' => 'sitemaps#sitemap', format: :xml, as: :sitemap, constraints: { sitemap_file: /.*/ }

    get('/development_scenario', to: 'development_scenarios#perform') if Settings.development_panel
  end

  def consider_rest_of_routes_as_portfolios
    get '/:url', to: 'portfolios#show', as: 'show_portfolio'
  end

  draw_routes
  consider_rest_of_routes_as_portfolios

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  attr_accessor :incoming_url

  def index
    @client = Client.new
    session[:return_to] = nil
    session[:login_after] = nil
    @main_navigation_items_prepend = [MenuBuilder::MenuItem.new(I18n.t('header.commercial'), Settings.commercial_link)]
    @dont_include_application_css = true
    render
  end

  def designer_submission; end

end

app/helpers/home_helper.rb
module HomeHelper

  def faq_client_questions
    hello_link = { hello_email: mail_to(t('feedback_email')) }
    pictures_link = { pictures_email: mail_to(Settings.pictures_email) }
    [{ get_in_touch: hello_link },
     :what_is_interiorcrowd,
     :how_does_it_work,
     :what_is_crowdsourcing,
     :who_are_designers,
     :how_many_designers,
     :style_profile,
     :what_do_i_get,
     :i_want_two_things,
     :im_too_busy,
     :designer_can_help_me_with,
     { forgot_password: hello_link },
     { how_to_upload_additional_pictures: pictures_link }]
  end

  def faq_commercial_questions
    hello_link = { hello_email: mail_to(t('feedback_email')),
                   google_form: link_to('here', Settings.external_urls.google_forms.help_with_new_office, target: '_blank') }
    [{ how_does_it_work: hello_link },
     { what_type_of_commercial_projects: hello_link },
     :who_are_designers,
     :is_this_for_me,
     :we_need_everything_asap,
     :i_dont_have_time]
  end

  def faq_designer_questions
    []
  end

  def faq_item(faq_chapter, question)
    if question.kind_of?(Hash)
      question_name = question.keys[0].to_s
      answer_i18n_params = question.values[0]
    else
      question_name = question.to_s
      answer_i18n_params = {}
    end
    { question: t("faq.#{ faq_chapter }.#{ question_name }.question"),
      answer: t("faq.#{ faq_chapter }.#{ question_name }.answer", answer_i18n_params) }
  end

  def need_help_path
    return faq_path if current_user.anonymous?
    return faq_path + '#designer' if current_user.designer?
    faq_path + '#client'
  end

  def enlarge_icon_path
    '/assets/icons/enlarge.png'
  end

  def download_icon_path
    '/assets/icons/download.png'
  end

  def remove_icon_path
    '/assets/cross-white.png'
  end

  def todays_client_stories
    @client_stories ||= I18n.t('home.client_stories.stories').rotate(Date.today.yday)
    @client_stories
  end
end

app/views/home/index/_bottom_carousel.html.haml
.container1
  #bottomCarouselHome.carousel.slide.carousel-fade{"data-ride" => "carousel"}
    / Indicators
    %ol.carousel-indicators.visible-xs
      %li{"data-slide-to" => "0", "data-target" => "#bottomCarouselHome"}
      %li.active{"data-slide-to" => "1", "data-target" => "#bottomCarouselHome"}
      %li{"data-slide-to" => "2", "data-target" => "#bottomCarouselHome"}
      %li{"data-slide-to" => "3", "data-target" => "#bottomCarouselHome"}
    / Wrapper for slides
    .carousel-inner{:role => "listbox"}
      .item
        %img#test{"data-original": "/assets/kirsten-room1.jpg"}/
        .carousel-caption
          %div
            %h5 Kirsten
            %p
              %span “
              As soon as the process began, I felt instantly inspired to go out and buy all the new furniture the designer recommended for my space. It was so easy! 
              %span ”
      .item.active
        %img#test{"data-original": "/assets/cathy-room1.jpg"}/
        .carousel-caption
          %div
            %h5 Cathy
            %p
              %span “
              I never felt comfortable in this room - there were just too many things wrong with it. Now, it brings me a lot of joy to be in this room. 
              %span ”
      .item
        %img#test{"data-original": "/assets/kevin-room1.jpg"}/
        .carousel-caption
          %div
            %h5 Kevin
            %p
              %span “
              Our priorities changed a lot when we had kids and our home became cluttered. Our designer provided some amazing solutions that were both practical - and nice to look at. 
              %span ”
      .item
        %img#test{"data-original": "/assets/melanie-room1.jpg"}/
        .carousel-caption
          %div
            %h5 Melanie
            %p
              %span “
              I always thought an interior designer would be too expensive, so I didn’t even consider it. My designer worked with my busy schedule - and it was actually fun! 
              %span ”
    / Controls
    %a.left.carousel-control.hidden-xs{"data-slide" => "prev",
        :href => "#bottomCarouselHome",
        :role => "button",
        :style => "margin-left: 375px;"}
      %img{:src => "/assets/carouselPrev.png"}/
    %a.right.carousel-control.hidden-xs{"data-slide" => "next",
        :href => "#bottomCarouselHome",
        :role => "button",
        :style => "margin-right: 375px;"}
      %img{:src => "/assets/carouselNext.png"}/
  .getStartedBottom.container
    .form-description.col-md-6.col-xs-12
      %h2= t('home.bottom.header')
      %h4= t('home.bottom.description')
    .form-body.col-md-6.col-xs-12
      = form_for @client, { url: ssl_sign_up_with_email_clients_path, method: 'post' } do |f|
        %label.col-xs-12= t('home.about_us.signup_form.name')
        = f.text_field :name, class: 'col-xs-12 form-control'
        %label.col-xs-12= t('home.about_us.signup_form.email')
        = f.text_field :email, class: 'col-xs-12 form-control'
        .error-message
          %span{ id: 'err_email' }
        %label.col-xs-12= t('home.about_us.signup_form.password')
        = f.password_field :password, class: 'col-xs-12 form-control'
        .error-message
          %span{ id: 'err_passwd' }
        %label.col-xs-12= t('home.about_us.signup_form.phone')
        = f.text_field :phone_number, class: 'col-xs-12 form-control'
        .form-button.col-xs-12
          %a.sign-up-from-homepage{ href: '#' }
            %span= t('home.get_started').upcase
            %img.arrow{ src: '/assets/go_right.png' }
  #scrollingAnchor

:javascript
  function loadCSS(href){
    var ss = window.document.createElement('link'),
        ref = window.document.getElementsByTagName('head')[0];

    ss.rel = 'stylesheet';
    ss.href = href;

    // temporarily, set media to something non-matching to ensure it'll
    // fetch without blocking render
    ss.media = 'only x';

    ref.parentNode.insertBefore(ss, ref);

    setTimeout( function(){
      // set media back to `all` so that the stylesheet applies once it loads
      ss.media = 'all';
    },0);
  }
  loadCSS('/assets/home/designer_stories.css.scss');
  loadCSS('/assets/application.css');

app/views/home/index/_carousel_shared_content.html.haml
.carousel-shared-content.carousel-caption
  .content
    .main-title= t('home.carousel.main_title')
    %a.getStartedBtn{ href: '#bottomCarouselHome' }
      %span= t('home.get_started').upcase
      %img.arrow{ src: '/assets/go_right.png' }
  .detailsContainer
    .details
      %span.detail= t('home.carousel.price', price: the_only_package.price).upcase
      %span|
      %span.detail= t('home.carousel.choose_designer').upcase
      %span|
      %span.detail= t('home.carousel.fun_and_easy').upcase

app/views/home/index/_designers.html.haml
%a.circleDownArrow.hidden-sm.hidden-xs{ href: 'javascript:void(0)' }
.container
  .row
    %h2= t('home.our_network.title')
    %p.title-border= t('home.our_network.description')
    .shortUnderline.marginBottom40

.container.designers-slider

  - t('home.our_network.designers').each_with_index do |designer, index|
    .theDesigner
      .design-example{ "data-original": "/assets/our_designers/design-#{ index + 1 }.jpg",
                       style: "background-image: url('/assets/our_designers/design-1.jpg');" }
      .image-container
        %img{ "data-lazy": "/assets/our_designers/personal-#{ index + 1 }.png" }
        %h4= designer[:name]
      .clearfix
      %p= designer[:wording]

app/views/home/index/_stories.html.haml
%h2= t('home.client_stories.title')
.shortUnderline.marginBottom40
.container-fluid.client-stories
  .client-bg-slider-wrapper
    .client-bg-slider
      - todays_client_stories.each do |story|
        .client-bg-slide{ "data-original":"/assets/client_stories/designed-for-#{ story[:name].downcase }.jpeg",
                          style: "background: url('/assets/client_stories/designed-for-helene.jpeg') no-repeat center; background-size: cover;" }
  .container
    .row
      .col-xs-12.col-xs-offset-0.col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3.col-lg-4.col-lg-offset-8
        .client-stories-slider
          - todays_client_stories.each do |story|
            %div
              .client-stories-slider-outer
                .client-stories-slider-inner
                  %img{ "data-lazy": "/assets/client_stories/#{ story[:name].downcase }-personal.png" }
                  %h4= story[:name].possessive + t('home.client_stories.story_title_constant_part')
                  .slider-delimiter
                  %p= story[:wording]
                  .slider-delimiter
                  %a{ href: "http://www.interiorcrowd.com/blog/#{ story[:blog_post].downcase }", target: '_blank' }
                    = t('home.client_stories.read_more_about', pronoun: story[:pronoun] )

app/views/home/index/_top_carousel.html.haml
#topCarouselHome.carousel.slide.carousel-fade{"data-ride" => "carousel"}
  / Indicators
  %ol.carousel-indicators
    %li.active{"data-slide-to" => "0", "data-target" => "#topCarouselHome"}
    %li{"data-slide-to" => "1", "data-target" => "#topCarouselHome"}
    %li{"data-slide-to" => "2", "data-target" => "#topCarouselHome"}
  / Wrapper for slides
  .carousel-inner{:role => "listbox"}
    .item.active
      .image-container{ style: 'background: linear-gradient(to bottom, rgba(0,0,0,.65) 0%, transparent 50%),
                                url("/assets/bedroom1.jpg") center center no-repeat; background-size: cover;' }
      = render 'home/index/carousel_shared_content'
    .item
      .image-container{ style: 'background: linear-gradient(to bottom, rgba(0,0,0,.65) 0%, transparent 50%),
                                url("/assets/Helene03.jpg") center; background-size: cover;' }
      = render 'home/index/carousel_shared_content'
    .item
      .image-container{ style: 'background: linear-gradient(to bottom, rgba(0,0,0,.65) 0%, transparent 50%),
                                url("/assets/Livingroom04.jpg") center; background-size: cover;' }
      = render 'home/index/carousel_shared_content'
  / Controls
  %a.left.carousel-control{"data-slide" => "prev", :href => "#topCarouselHome", :role => "button"}
    %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
    %span.sr-only Previous
  %a.right.carousel-control{"data-slide" => "next", :href => "#topCarouselHome", :role => "button"}
    %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
    %span.sr-only Next
.bottom-details
  %span.detail= t('home.carousel.price', price: the_only_package.price).upcase
  %br
  %span.detail= t('home.carousel.choose_designer').upcase
  %br
  %span.detail= t('home.carousel.fun_and_easy').upcase

app/views/home/index/_what_to_expect.html.haml
.container
  %h2= t('home.what_to_expect.header').upcase
  - what_to_expect_link = link_to(t('home.what_to_expect.see_here'), faq_path(anchor: 'client'))
  .subtitle= t('home.what_to_expect.more_info', see_here: what_to_expect_link).html_safe
  .shortUnderline.marginBottom40
  .row.text-center
    .col-sm-6.col-lg-4
      %img{:src => "/assets/Vector-Smart-Object.png"}/
      %h5= t('home.what_to_expect.multiple_concepts.title')
      %p= t('home.what_to_expect.multiple_concepts.description')
    .col-sm-6.col-lg-4
      %img{:src => "/assets/Vector-Smart-Object1.png"}/
      %h5= t('home.what_to_expect.collaborate_with_professionals.title')
      %p= t('home.what_to_expect.collaborate_with_professionals.description')
    .col-sm-6.col-lg-4
      %img{:src => "/assets/Vector-Smart-Object2.png"}/
      %h5= t('home.what_to_expect.customized_design.title')
      %p= t('home.what_to_expect.customized_design.description')

    .col-sm-6.col-sm-offset-0.col-lg-3.col-lg-offset-2
      %img{:src => "/assets/Vector-Smart-Object3.png"}/
      %h5= t('home.what_to_expect.easy_instructions.title')
      %p= t('home.what_to_expect.easy_instructions.description')
    .col-sm-8.col-sm-offset-2.col-lg-7.col-lg-offset-0
      %img{:src => "/assets/Vector-Smart-Object4.png"}/
      %h5= t('home.what_to_expect.shopping_list.title')
      %p= t('home.what_to_expect.shopping_list.description')

app/views/home/index/_what_we_do.html.haml
.container
  %h2= t('home.what_we_do.title')
  .shortUnderline
  %p= t('home.what_we_do.wording')
  .clearfix
  .bottomBar.hidden-xs
    %hr#left-line
    .rounded-box
      = t('home.what_we_do.home')
      %span.what-we-do-separator= '|'
      = t('home.what_we_do.office')
      %span.what-we-do-separator= '|'
      = t('home.what_we_do.person')
    %hr#right-line
  .bottomBarMobile.visible-xs
    = t('home.what_we_do.home')
    %hr
    = t('home.what_we_do.office')
    %hr
    = t('home.what_we_do.person')