config/routes.rb
InteriorC::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  def draw_routes
    root 'home#index'

    resources :designers, only: [:new, :create, :update]

    resources :sessions, only: [] do
      collection do
        get 'logout'
        get 'designer_login'
        get 'client_login'
        post 'client_authenticate'
        get 'client_fb_authenticate'
        post 'authenticate'
        match 'designer_retry_password', via: [:post, :get]
        match 'client_retry_password', via: [:post, :get]
      end
    end

    get 'terms_of_service', to: 'home#terms_of_service'
    get 'faq', to: 'home#faq'
    get 'sign_up_beta', to: 'home#sign_up_beta'
    get 'how_it_works', to: 'home#how_it_works'
    get 'about_us', to: 'home#about_us'

    resources :contest_requests, only: [:show, :create] do
      resources :comments, controller: :concept_board_comments, only: [:create, :update, :destroy]
      member do
        get 'save_lookbook'
        post 'answer'
        post 'approve_fulfillment'
        get 'download'
      end
    end

    resources :contests, only: [:show, :update] do
      member do
        get 'option'
        get 'show', as: 'show'
        get 'brief', to: 'clients#brief', as: 'brief'
        get 'download_all_images_url'
        get 'design_brief'
        post 'save_design_brief'
        get 'design_style'
        post 'save_design_style'
        get 'design_space'
        post 'save_design_space'
        get 'preview'
        post 'save_preview'
        get 'image_items'
        resources :feedback,
                  controller: 'reviewer_feedbacks',
                  as: 'reviewer_feedbacks',
                  only: [:create] do

          collection do
            get '', to: 'reviewer_feedbacks#show', as: 'show'
          end
        end
      end

      collection do
        get 'design_brief'
        post 'save_design_brief'
        get 'design_style'
        post 'save_design_style'
        get 'design_space'
        post 'save_design_space'
        get 'preview'
        post 'save_preview'
        post 'upload'
        get 'invite_designers'
        get 'account_creation'
        get 'payment_details'
        get 'payment_summary'
        put 'save_intake_form'
      end

      resource :time_tracker do
        get '/', to: 'time_tracker#designer_view', as: 'designer_center'
        post 'suggest_hours', to: 'time_tracker#suggest_hours', as: 'suggest_hours'
        resources :designer_activities, only: [:create] do
          resources :comments, only: [:create], controller: 'designer_activity_comments'

          member do
            patch 'read', to: 'designer_activities#read'
          end
        end
        resources :attachments, only: [:create], controller: 'time_tracker_attachments'
      end
    end

    resources :images, only: [] do
      collection do
        get 'ready', to: 'images#ready'
        post 'sign', to: 'images#sign'
        post 'on_uploaded', to: 'images#on_uploaded'
      end
    end

    resources :clients, only: [:create, :update] do
      collection do
        get 'validate_card'
        post 'sign_up_with_facebook'
        post 'sign_up_with_email'
        post 'ssl_sign_up_with_email'
        get 'unsubscribe/:signature', to: 'clients#unsubscribe', as: 'unsubscribe'
      end
    end

    scope '/client_center' do
      resources :entries, only: [:index, :show], controller: 'contests', as: 'client_center_entries' do
        member do
          get 'time_tracker', to: 'time_tracker#client_view', as: 'time_tracker'
          post 'time_tracker/initialize_purchase', to: 'time_tracker#initialize_purchase', as: 'time_tracker_initialize_purchase'
          post 'time_tracker/confirm_purchase', to: 'time_tracker#confirm_purchase', as: 'time_tracker_confirm_purchase'
        end
      end
      get '', to: 'clients#client_center', as: 'client_center'
      get 'concept_boards_page', to: 'clients#concept_boards_page', as: 'client_center_concept_boards_page'
      get 'profile', to: 'clients#profile', as: 'client_center_profile'
      get 'pictures_dimension', to: 'clients#pictures_dimension', as: 'client_center_pictures_dimension'
    end

    resources :designers, only: [:create, :update]

    scope '/designer_center' do
      get '', to: 'designer_center#designer_center', as: 'designer_center'
      get 'updates', to: 'designer_center#updates', as: 'designer_center_updates'
      get 'training', to: 'designer_center#training', as: 'designer_center_training'
      resources :contests,
                controller: 'designer_center_contests',
                as: 'designer_center_contest',
                only: [:show, :index] do
        resources :comments, controller: :concept_board_comments, only: [:create]
        collection do
          get 'index'
        end
      end
      resources :responses,
                controller: 'designer_center_requests',
                as: 'designer_center_response',
                only: [:new, :create, :show, :index, :update, :edit] do
        member do
          get 'preview', as: 'preview'
          patch 'publish', as: 'publish'
        end

        resources :lookbook_details, only: [:create, :destroy]
      end
      resource :portfolio, only: [:edit, :update]
    end

    resources :designer_invitations, only: [:create]
    resources :contest_notes, only: [:create]
    resources :reviewer_invitations, only: [:create]
    resources :beta_subscribers, only: [:create]
    resources :image_items, only: [:create, :update, :new, :edit, :destroy] do
      member do
        patch 'mark', to: 'image_items#mark', as: 'mark'
      end
      collection do
        get 'default', to: 'image_items#default', as: 'default'
      end
    end
    resource :designs do
      get '/:token', to: 'contest_requests#design', as: 'public'
    end
    resources :notifications, only: [:show] do
      collection do
        get '/comments/:id', to: 'notifications#show_comment', as: 'comment'
      end
    end

    resources :promocodes, only: [] do
      collection do
        get '', to: 'promocodes#apply', as: 'apply'
      end
    end

    resources :lookbook_details, only: [] do
      collection do
        get '/preview', to: 'lookbook_details#preview', as: 'preview'
        delete '/remove_preview', to: 'lookbook_details#remove_preview', as: 'remove_preview'
      end
    end

    resources :final_notes,
              controller: 'final_notes',
              as: 'final_note',
              only: [:create]

    resources :credit_cards, only: [:create, :edit, :update, :destroy] do
      member do
        patch 'set_as_primary'
      end
    end

    resources :client_payments, only: [:create]

    get '/coming_soon', to: 'home#coming_soon', as: 'coming_soon'
    get '/privacy_policy', to: 'home#privacy_policy', as: 'privacy_policy'
    get '/designer_submission', to: 'home#designer_submission', as: 'designer_submission'
    get '/justines_story', to: 'blog#justines_story', as: 'justines_story'

    scope '/blog' do
      get '/', to: 'blog#blog_root', as: 'blog_root'
      get '/designers', to: 'blog#designers_blog_root', as: 'designers_blog_root'
      get '/designers/:blog_page_path',
          to: 'blog#designers_blog_page',
          as: 'designers_blog_page',
          constraints: { blog_page_path: /.*/ }
      post '/designers/:blog_page_path',
           to: 'blog#designers_blog_page_post',
           as: 'designers_blog_page_post',
           constraints: { blog_page_path: /.*/ }
      get '/:blog_page_path',
          to: 'blog#blog_page',
          as: 'blog_page',
          constraints: { blog_page_path: /.*/ }
      post '/:blog_page_path',
           to: 'blog#blog_page_post',
           as: 'blog_page_post',
           constraints: { blog_page_path: /.*/ }
    end

    resources :outbound_emails, :controller => 'email_webhooks', :only => [:show, :create]
    get '/outbound_emails', to: 'email_webhooks#verify', via: :head

    resources :giftcard_payments, controller: 'giftcard_payments', only: [:create, :index]

    get '/sfar', to: 'realtor_contacts#sfar', as: 'sfar'
    get '/giftcards', to: 'giftcard_payments#new', as: 'new_giftcard_payment'

    resources :realtor_contacts, only: [:create]

    get 'sitemap.xml' => 'sitemaps#sitemap_index', format: :xml, as: :sitemap_index
    get 'sitemap_index.xml' => 'sitemaps#sitemap_index', format: :xml
    get 'sitemaps/:sitemap_file' => 'sitemaps#sitemap', format: :xml, as: :sitemap, constraints: { sitemap_file: /.*/ }

    get('/development_scenario', to: 'development_scenarios#perform') if Settings.development_panel
  end

  def consider_rest_of_routes_as_portfolios
    get '/:url', to: 'portfolios#show', as: 'show_portfolio'
  end

  draw_routes
  consider_rest_of_routes_as_portfolios

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  attr_accessor :incoming_url

  def index
    @client = Client.new
    session[:return_to] = nil
    session[:login_after] = nil
    @main_navigation_items_prepend = [MenuBuilder::MenuItem.new(I18n.t('header.commercial'), Settings.commercial_link)]
    @dont_include_application_css = true
    render
  end

  def designer_submission; end

end

app/helpers/home_helper.rb
module HomeHelper

  def faq_client_questions
    hello_link = { hello_email: mail_to(t('feedback_email')) }
    pictures_link = { pictures_email: mail_to(Settings.pictures_email) }
    [{ get_in_touch: hello_link },
     :what_is_interiorcrowd,
     :how_does_it_work,
     :what_is_crowdsourcing,
     :who_are_designers,
     :how_many_designers,
     :style_profile,
     :what_do_i_get,
     :i_want_two_things,
     :im_too_busy,
     :designer_can_help_me_with,
     { forgot_password: hello_link },
     { how_to_upload_additional_pictures: pictures_link }]
  end

  def faq_commercial_questions
    hello_link = { hello_email: mail_to(t('feedback_email')),
                   google_form: link_to('here', Settings.external_urls.google_forms.help_with_new_office, target: '_blank') }
    [{ how_does_it_work: hello_link },
     { what_type_of_commercial_projects: hello_link },
     :who_are_designers,
     :is_this_for_me,
     :we_need_everything_asap,
     :i_dont_have_time]
  end

  def faq_designer_questions
    []
  end

  def faq_item(faq_chapter, question)
    if question.kind_of?(Hash)
      question_name = question.keys[0].to_s
      answer_i18n_params = question.values[0]
    else
      question_name = question.to_s
      answer_i18n_params = {}
    end
    { question: t("faq.#{ faq_chapter }.#{ question_name }.question"),
      answer: t("faq.#{ faq_chapter }.#{ question_name }.answer", answer_i18n_params) }
  end

  def need_help_path
    return faq_path if current_user.anonymous?
    return faq_path + '#designer' if current_user.designer?
    faq_path + '#client'
  end

  def enlarge_icon_path
    '/assets/icons/enlarge.png'
  end

  def download_icon_path
    '/assets/icons/download.png'
  end

  def remove_icon_path
    '/assets/cross-white.png'
  end

  def todays_client_stories
    @client_stories ||= I18n.t('home.client_stories.stories').rotate(Date.today.yday)
    @client_stories
  end
end

app/views/home/_designer_contract.html.haml
.terms-of-services.lightFont
  .marg-top Come now, InteriorCrowd, Inc. (“InteriorCrowd”), and you (“Designer”) and enter into this contract and agreement as follows:
  .marg-top.text-center WHEREAS
  .marg-top WHEREAS, InteriorCrowd has entered into relationships with clients (“Clients”) to provide interior design and technology services for specified projects through InteriorCrowd (“Projects” or “Contests”).
  .marg-top WHEREAS, Projects and/or Contests generally proceed as follows:
  %ul
    %li{type: 'a'} Designers may submit design concepts (“Concept Boards”) in the format specified by InteriorCrowd following instructions on the Site. Clients must select one winning design within a specified period of time.
    %li{type: 'a'} If / when a Client chooses a winning design, the chosen Designer will be notified (the “Winner”). The Winner shall conduct the initial one hour consultation (the “Initial Consultation”) as soon as practicable. Initial Consultations shall be conducted in-person unless this is not feasible for the Client.  This will involve such things as communicating with the Client through the Site to determine a time convenient for both parties, having the consultation to better assess the client’s needs, and following up with InteriorCrowd about the estimated size and scope of the project (“Scope of Work”).
    %li{type: 'a'} Based on the Scope of Work, the Client may elect to purchase hours of design services (“Design Services”) to move from a Concept Board to a final design (the “Final Design”). This includes development of a list of products that meet the Client’s needs and budget (the “Product List” or “Shopping List”) as well as other requirements that may be communicated through the Site or otherwise. Designers may also need to create a 3D rendering, a floor plan, a spatial plan, drawings, or other items as required by the Client or InteriorCrowd as specified.  Designers may also be involved in project management services, oversight of third parties involved in a project, and otherwise as may be typical or necessary in the Scope of Work;
  .marg-top WHEREAS, Client(s) may elect, through its relationship with InteriorCrowd (“Contract”), to use the services of Designer to complete the Scope of Work;
  .marg-top Therefore, the parties hereto covenant and agree as follows:
  %ul
    %li{type: '1'} That Designer shall provide all time, materials, and other input necessary to complete the Scope of Work as set out in said contract.
    %li{type: '1'} That the Terms of Service and End User License Agreement previously entered into between InteriorCrowd and Designer is likewise incorporated into and made part of this agreement.
    %li{type: '1'} That Designer is an Independent Contractor and is not and will not be considered to be an employee of InteriorCrowd for any reason or purpose. InteriorCrowd does not control the time, manner, or method of the services provided by Designer, other than to require that Designer comply with the requirements and provisions contained in the Scope of Work of said Contract.
    %li{type: '1'} That Designer shall perform such work in a timely and professional manner so as to allow InteriorCrowd to fully and completely perform its obligations to Client under said Contract.
    %li{type: '1'} That if Designer, in the sole discretion of InteriorCrowd, is unable or unwilling to completely fulfill the requirements of said Contract, InteriorCrowd reserves the right to retain other designers or personnel to help, supplement, or replace Designer in completing the requirements of said Contract.
    %li{type: '1'} That Designer shall be remunerated at a rate of 70% of the fee(s) paid by the Client for the Design Services, less the credit card processing fees, for work performed under this agreement. It being clearly understood by Designer that there shall be no remuneration for fees paid by the Client, if any, for the Concept Boards and Initial Consultation.  Any and all fee amounts are subject to change by InteriorCrowd upon notice to the Designer. Invoices for work shall be submitted monthly to InteriorCrowd and will be due and payable within 15 days of receipt by InteriorCrowd. Any advances or expenses may be submitted for reimbursement immediately upon being incurred and will likewise be due and payable within 15 days of receipt by InteriorCrowd.  Designer will be paid either electronically or via check.
    %li{type: '1'} In the case of a Refund or lack of payment due primarily to a Client’s disagreement or disappointment I the Designer’s services, InteriorCrowd has the right to reimbursement by the Designer for the fees paid. Reimbursement will first come from any earnings accrued by the Designer but not yet paid; to the extent that the earnings are not sufficient to cover the reimbursement, InteriorCrowd has the right to reimbursement on demand.
    %li{type: '1'} That Designer shall submit all purchase orders for furniture, fixtures, equipment or materials directly to InteriorCrowd, which will arrange with Client for all payments, advances and deposits. Designer may coordinate all appropriate shipping, delivery and installation of same as agreed to by the parties.
    %li{type: '1'} That InteriorCrowd may terminate this agreement, upon 15 days written notice to Designer, if the Client is dissatisfied with Designer’s services, or, in the sole discretion of InteriorCrowd, Designer has failed to comply with her obligations under this agreement.
    %li{type: '1'} That if Designer fails to perform her obligations under this agreement, with the result that the Client seeks reimbursement or damages of any sort from InteriorCrowd, Designer will save and hold harmless InteriorCrowd from any claims which result from the negligence, inattention, or other actions of Designer, including any and all attorneys’ fees and costs incurred by InteriorCrowd.
    %li{type: '1'} That Designer hereby conveys any and all rights, including copyrights, to any and all concepts, drawings, plans, photographs or materials prepared under this agreement to InteriorCrowd. InteriorCrowd will grant to Designer a non-exclusive license to use said photographs for her business purposes. However, the Designer shall not disclose the Client’s identification or address without prior written consent.
    %li{type: '1'} That the Designer may not assign or sub-contract any obligation or provision of this agreement without the prior written consent of InteriorCrowd.
    %li{type: '1'} That this agreement is the full and complete statement of understanding between Designer and InteriorCrowd and may not be changed or modified except in writing signed by both parties hereto.
    %li{type: '1'} That this agreement shall be governed and construed in accordance with the laws of the State of California.
    %li{type: '1'} The parties agree that any disputes or controversies arising out of this shall be subject to mediation as a precondition to arbitration. Said mediation shall take place in San Francisco, CA, using a mediator mutually agreed to by the parties, with the parties to bear their own costs, including attorneys’ fees. In the event the matter cannot be resolved by mediation, it shall be settled by arbitration administered by the American Arbitration Association under its Commercial Arbitration Rules.
    %li{type: '1'} That if any provision of this agreement shall be held, by a court of competent jurisdiction, to be void or unenforceable, any and all remaining provisions shall continue to be valid and binding on the parties hereto.

app/views/home/_designer_contract_modal.html.haml
#designer_contract_modal.modal.fade{ aria: { hidden: 'true' }, role: 'dialog', tabindex: '-1' }

  .modal-dialog
    .modal-content
      .modal-header
        %h4.modal-title= t('terms_of_service.designer_contract')
        %button.close.close-modal{"data-dismiss" => "modal", :type => "button"} ×
      .modal-body
        %p.SofiaProLight= render partial: 'home/designer_contract'
        .text-center
          %button.btn1.btn1-confirm.close-btn{"data-dismiss" => "modal", :type => "button"}
            = t('terms_of_service.close')


:javascript
  $('.designer-contract').on('click', function(){
    $('#designer_contract_modal').modal('show')
    mixpanel.track('Button clicked', { name: 'Designer - Designer contract' })
  })

app/views/home/_development_panel.html.haml
- if @development_scenarios
  - @development_scenarios.each_with_index do |scenario, index|
    %a{ href: scenario[:scenario_class].path(self, scenario_method: scenario[:scenario_method]) }= scenario[:name]
    - unless index == @development_scenarios.length - 1
      *

app/views/home/_msg.html.haml
%div
  - if flash[:error].present?
    .alert.alert-danger= flash[:error].html_safe
  - if flash[:alert].present?
    .alert.alert-danger= flash[:alert].html_safe
  - if flash[:notice].present?
    .alert.alert-success= flash[:notice].html_safe

app/views/home/_navigation_menu.haml
.col-md-3
  %ul.nav.faqNav{:role => "tablist"}
    %li.active{:role => "presentation"}
      %a{"aria-controls" => "customer", "data-toggle" => "tab", :href => "#customer", :role => "tab"}= t('.customer')
    %li{:role => "presentation"}
      %a{"aria-controls" => "designer", "data-toggle" => "tab", :href => "#designer", :role => "tab"}= t('.designer')
    %li{:role => "presentation"}
      %a{"aria-controls" => "commercial", "data-toggle" => "tab", :href => "#commercial", :role => "tab"}= t('.commercial')

app/views/home/about_us.html.haml
.no-js.template-about
  .main
    %header
    .spanning.clearfix
      .about-hero
        .about-hero-background{:style => "background-image: url('/assets/about_us/about-bg-1.jpg');"}
          .about-hero-title
            .wrap
              %h1= t('.title')

      = render 'home/about_us/what_we_do'

      = render 'home/about_us/team'

      = render 'home/about_us/designers'

      = render 'home/about_us/writers'

      = render 'home/about_us/job_opportunities'

app/views/home/coming_soon.html.haml
:css
  body { background-color: #F5F6F5 }
  #body-header, #body-footer, .copyright { background-color: white }

.container-fluid.text-center.pageNotFound{ style: 'height: 100%;' }
  .row
    .col-md-12
      %h1{ style: 'font-size: 50px; font-weight: bold; margin-top: 50px;' }= t('coming_soon.title')
      %p= t('coming_soon.subtitle')
      - back_url = (Rails.application.routes.recognize_path(request.referrer)[:action] == 'coming_soon') ? root_path : request.referrer
      = link_to t('coming_soon.go_back'), back_url, style: 'width: 200px; padding: 10px', class: "btn #{ tracked_link }", data: { name: 'Coming Soon page - Go Back' }

app/views/home/designer_submission.html.haml
%iframe{ frameborder: '0',
    height: '2700',
    marginheight: '0',
    marginwidth: '0',
    src: Settings.designer_submission_iframe_source,
    width: '100%' }
  Loading...

app/views/home/faq.html.haml
- content_for :head do
  = javascript_include_tag 'home/faq'

.container.animated.fadeInDown.marg-top40.lightFont
  .row.borderBottom
    .col-md-6
      %h2= t('.title')
    .col-md-6.text-right
      #searchBox
        = text_field_tag 'search', nil, placeholder: t('.search_field_placeholder')
        %button
          = image_tag '/assets/magnifier.png'
  .row.marg-top20.bottom60
    .col-md-12
      .row.tabpanel.padd50Side
        = render :partial => 'navigation_menu'
        .col-md-9
          .tab-content
            = render partial: 'home/faq/customer'
            = render partial: 'home/faq/designer'
            = render partial: 'home/faq/commercial'

app/views/home/how_it_works.html.haml
.main.how-it-works-container
  %header
  .spanning.clearfix
    .how-it-works-hero{:style => "background-image: url('/assets/how_it_works/how_it_works_hero.jpg');"}
      .how-it-works-hero-gradient
        .wrap
          .how-it-works-hero-title= t('.title')
    .get-started-navigation
      .wrap
        %p= t('.get_started_text')
        = link_to t('.get_started_link'), design_brief_contests_path, class: 'button-get-started'
    .how-it-works-lead
      .wrap
        .how-it-works-lead-wrapper
          %p= t('.lead_wrapper').html_safe
    = render 'home/how_it_works/steps'
    = render 'home/how_it_works/faq'
%footer

app/views/home/index.html.haml
- content_for :head do
  = javascript_include_tag 'home/main', async: Rails.env.production?

  :javascript
    Messages = #{ translations_to_json(['home', 'sign_up_form']) }

.sticky-nav
  .row
    .col.col-xs-7.col-sm-8
      %h5= t('home.sticky_nav.description')
    .col.col-xs-5.col-sm-4
      %a.getStartedSticky{ href: '#', class: tracked_link }
        %span= t('home.get_started').upcase

= render 'shared/pinterest_tracking', id: Settings.pinterest.landing_tracking_id

.homepage
  .container-fluid.topCarouselHome
    = render 'home/index/top_carousel'

  .container-fluid.padding-section.our-network.container-fluid.wrapper-designers-slider
    = render 'home/index/designers'

  .container-fluid.whatWeDoBox
    = render 'home/index/what_we_do'

  .container-fluid.clientStories
    = render 'home/index/stories'

  .container-fluid.whatToExpect
    = render 'home/index/what_to_expect'

  .container-fluid.bottomCarouselHome
    = render 'home/index/bottom_carousel'

app/views/home/terms_of_service.html.haml
.container.animated.fadeInDown
  = render partial: 'home/terms_of_service'
  %br
  %br
  .marg-top= t('terms_of_service.designer_contract').capitalize
  = render partial: 'home/designer_contract'