config/routes.rb
InteriorC::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  def draw_routes
    root 'home#index'

    resources :designers, only: [:new, :create, :update]

    resources :sessions, only: [] do
      collection do
        get 'logout'
        get 'designer_login'
        get 'client_login'
        post 'client_authenticate'
        get 'client_fb_authenticate'
        post 'authenticate'
        match 'designer_retry_password', via: [:post, :get]
        match 'client_retry_password', via: [:post, :get]
      end
    end

    get 'terms_of_service', to: 'home#terms_of_service'
    get 'faq', to: 'home#faq'
    get 'sign_up_beta', to: 'home#sign_up_beta'
    get 'how_it_works', to: 'home#how_it_works'
    get 'about_us', to: 'home#about_us'

    resources :contest_requests, only: [:show, :create] do
      resources :comments, controller: :concept_board_comments, only: [:create, :update, :destroy]
      member do
        get 'save_lookbook'
        post 'answer'
        post 'approve_fulfillment'
        get 'download'
      end
    end

    resources :contests, only: [:show, :update] do
      member do
        get 'option'
        get 'show', as: 'show'
        get 'brief', to: 'clients#brief', as: 'brief'
        get 'download_all_images_url'
        get 'design_brief'
        post 'save_design_brief'
        get 'design_style'
        post 'save_design_style'
        get 'design_space'
        post 'save_design_space'
        get 'preview'
        post 'save_preview'
        get 'image_items'
        resources :feedback,
                  controller: 'reviewer_feedbacks',
                  as: 'reviewer_feedbacks',
                  only: [:create] do

          collection do
            get '', to: 'reviewer_feedbacks#show', as: 'show'
          end
        end
      end

      collection do
        get 'design_brief'
        post 'save_design_brief'
        get 'design_style'
        post 'save_design_style'
        get 'design_space'
        post 'save_design_space'
        get 'preview'
        post 'save_preview'
        post 'upload'
        get 'invite_designers'
        get 'account_creation'
        get 'payment_details'
        get 'payment_summary'
        put 'save_intake_form'
      end

      resource :time_tracker do
        get '/', to: 'time_tracker#designer_view', as: 'designer_center'
        post 'suggest_hours', to: 'time_tracker#suggest_hours', as: 'suggest_hours'
        resources :designer_activities, only: [:create] do
          resources :comments, only: [:create], controller: 'designer_activity_comments'

          member do
            patch 'read', to: 'designer_activities#read'
          end
        end
        resources :attachments, only: [:create], controller: 'time_tracker_attachments'
      end
    end

    resources :images, only: [] do
      collection do
        get 'ready', to: 'images#ready'
        post 'sign', to: 'images#sign'
        post 'on_uploaded', to: 'images#on_uploaded'
      end
    end

    resources :clients, only: [:create, :update] do
      collection do
        get 'validate_card'
        post 'sign_up_with_facebook'
        post 'sign_up_with_email'
        post 'ssl_sign_up_with_email'
        get 'unsubscribe/:signature', to: 'clients#unsubscribe', as: 'unsubscribe'
      end
    end

    scope '/client_center' do
      resources :entries, only: [:index, :show], controller: 'contests', as: 'client_center_entries' do
        member do
          get 'time_tracker', to: 'time_tracker#client_view', as: 'time_tracker'
          post 'time_tracker/initialize_purchase', to: 'time_tracker#initialize_purchase', as: 'time_tracker_initialize_purchase'
          post 'time_tracker/confirm_purchase', to: 'time_tracker#confirm_purchase', as: 'time_tracker_confirm_purchase'
        end
      end
      get '', to: 'clients#client_center', as: 'client_center'
      get 'concept_boards_page', to: 'clients#concept_boards_page', as: 'client_center_concept_boards_page'
      get 'profile', to: 'clients#profile', as: 'client_center_profile'
      get 'pictures_dimension', to: 'clients#pictures_dimension', as: 'client_center_pictures_dimension'
    end

    resources :designers, only: [:create, :update]

    scope '/designer_center' do
      get '', to: 'designer_center#designer_center', as: 'designer_center'
      get 'updates', to: 'designer_center#updates', as: 'designer_center_updates'
      get 'training', to: 'designer_center#training', as: 'designer_center_training'
      resources :contests,
                controller: 'designer_center_contests',
                as: 'designer_center_contest',
                only: [:show, :index] do
        resources :comments, controller: :concept_board_comments, only: [:create]
        collection do
          get 'index'
        end
      end
      resources :responses,
                controller: 'designer_center_requests',
                as: 'designer_center_response',
                only: [:new, :create, :show, :index, :update, :edit] do
        member do
          get 'preview', as: 'preview'
          patch 'publish', as: 'publish'
        end

        resources :lookbook_details, only: [:create, :destroy]
      end
      resource :portfolio, only: [:edit, :update]
    end

    resources :designer_invitations, only: [:create]
    resources :contest_notes, only: [:create]
    resources :reviewer_invitations, only: [:create]
    resources :beta_subscribers, only: [:create]
    resources :image_items, only: [:create, :update, :new, :edit, :destroy] do
      member do
        patch 'mark', to: 'image_items#mark', as: 'mark'
      end
      collection do
        get 'default', to: 'image_items#default', as: 'default'
      end
    end
    resource :designs do
      get '/:token', to: 'contest_requests#design', as: 'public'
    end
    resources :notifications, only: [:show] do
      collection do
        get '/comments/:id', to: 'notifications#show_comment', as: 'comment'
      end
    end

    resources :promocodes, only: [] do
      collection do
        get '', to: 'promocodes#apply', as: 'apply'
      end
    end

    resources :lookbook_details, only: [] do
      collection do
        get '/preview', to: 'lookbook_details#preview', as: 'preview'
        delete '/remove_preview', to: 'lookbook_details#remove_preview', as: 'remove_preview'
      end
    end

    resources :final_notes,
              controller: 'final_notes',
              as: 'final_note',
              only: [:create]

    resources :credit_cards, only: [:create, :edit, :update, :destroy] do
      member do
        patch 'set_as_primary'
      end
    end

    resources :client_payments, only: [:create]

    get '/coming_soon', to: 'home#coming_soon', as: 'coming_soon'
    get '/privacy_policy', to: 'home#privacy_policy', as: 'privacy_policy'
    get '/designer_submission', to: 'home#designer_submission', as: 'designer_submission'
    get '/justines_story', to: 'blog#justines_story', as: 'justines_story'

    scope '/blog' do
      get '/', to: 'blog#blog_root', as: 'blog_root'
      get '/designers', to: 'blog#designers_blog_root', as: 'designers_blog_root'
      get '/designers/:blog_page_path',
          to: 'blog#designers_blog_page',
          as: 'designers_blog_page',
          constraints: { blog_page_path: /.*/ }
      post '/designers/:blog_page_path',
           to: 'blog#designers_blog_page_post',
           as: 'designers_blog_page_post',
           constraints: { blog_page_path: /.*/ }
      get '/:blog_page_path',
          to: 'blog#blog_page',
          as: 'blog_page',
          constraints: { blog_page_path: /.*/ }
      post '/:blog_page_path',
           to: 'blog#blog_page_post',
           as: 'blog_page_post',
           constraints: { blog_page_path: /.*/ }
    end

    resources :outbound_emails, :controller => 'email_webhooks', :only => [:show, :create]
    get '/outbound_emails', to: 'email_webhooks#verify', via: :head

    resources :giftcard_payments, controller: 'giftcard_payments', only: [:create, :index]

    get '/sfar', to: 'realtor_contacts#sfar', as: 'sfar'
    get '/giftcards', to: 'giftcard_payments#new', as: 'new_giftcard_payment'

    resources :realtor_contacts, only: [:create]

    get 'sitemap.xml' => 'sitemaps#sitemap_index', format: :xml, as: :sitemap_index
    get 'sitemap_index.xml' => 'sitemaps#sitemap_index', format: :xml
    get 'sitemaps/:sitemap_file' => 'sitemaps#sitemap', format: :xml, as: :sitemap, constraints: { sitemap_file: /.*/ }

    get('/development_scenario', to: 'development_scenarios#perform') if Settings.development_panel
  end

  def consider_rest_of_routes_as_portfolios
    get '/:url', to: 'portfolios#show', as: 'show_portfolio'
  end

  draw_routes
  consider_rest_of_routes_as_portfolios

end

app/helpers/client_center_helper.rb
module ClientCenterHelper

  def responses_filter_options
    { '' => t('client_center.entries.responses_filter_all') ,
      'favorite' => t('client_center.entries.answers.favorite'),
      'maybe' => t('client_center.entries.answers.maybe') ,
      'no' => t('client_center.entries.answers.no'),
      'winner' => t('client_center.entries.answers.winner') }
  end

  def show_time_button?
    false
  end

end

app/views/clients/client_center/entries/_design_item.haml
.row.marg-top30
  .col-md-5
    = image_tag image_item.thumb_url, class: 'productListIMG'
  .col-md-7
    - [:name, :brand, :dimensions, :price].each do |attribute|
      %p.font16.makeMeBlack.lineHeight25.margin0{ class: attribute.to_s }= image_item.send(attribute)
    = link_to image_item.link, image_item.link_href, target: '_blank', class: "font20 blueLink #{ tracked_link }", data: { name: 'Final design - product item link' }
.hLine10.marg-top30

app/views/clients/client_center/entries/_designer_to_invite.html.haml
.col-sm-6.profile-card{ data: { id: designer.id } }
  .row.designerBox
    .col-xs-5.avatarSide
      %a{ href: show_portfolio_path(designer.portfolio_path),
          class: tracked_link,
          data: { name: 'Portfolio (designer image)' } }
        %div.avatar{ style: "background-image: #{ css_url(designer.personal_picture_url) }" }
      = render partial: 'clients/client_center/entries/invite_designer_button',
          locals: { css_class: 'hide480', invited: designer.invited_to_contest?(@contest) }
    .col-xs-7.detailsSide
      %p.designerName
        = link_to(designer.name,
                  show_portfolio_path(designer.portfolio_path),
                  class: tracked_link,
                  data: { name: 'Portfolio (designer name)' })
      .fullWidthLine
      %p.designMindset= t('client_center.entries.designer_profile.about_title')
      %p.about.designerDesc= designer.about
      .fullWidthLine
      %p.designMindset= t('client_center.entries.designer_profile.style_specialty')
      %p.style.designerDesc= designer.style_description_texts
  = render partial: 'clients/client_center/entries/invite_designer_button',
      locals: { css_class: 'show480', invited: designer.invited_to_contest?(@contest) }

app/views/clients/client_center/entries/_designers_to_invite.html.haml
%p.daysAway
  = t('client_center.entries.signed_up_message')
  %span.mdLineBreaker
  = t('client_center.entries.signed_up_message_below')

- designers.in_groups_of(2, false) do |designers|
  .row.designers-row
    - designers.each do |designer|
      = render 'clients/client_center/entries/designer_to_invite', designer: designer
%a.seeMoreDesigners{ href: coming_soon_path, class: tracked_link }
  = t('client_center.entries.see_more_designers')

app/views/clients/client_center/entries/_final_design.haml
.winnerBadge
  %span
  %p Final Design
  .clearfix

= javascript_include_tag 'contest_requests/showcase'

= render 'designer_center_requests/showcase',
    showcase: Showcase.new(items: request.current_lookbook_items, editable: false)

app/views/clients/client_center/entries/_final_design_image_item.haml
.col-xs-6
  .itemBox
    .row
      .col-lg-6.col-sm-7.itemBoxLeft{ style: 'height: 264px;' }
        = render 'shared/image_with_enlarge_button',
            settings: EnlargeablePicture.new(image_class: 'full-size-image-container',
              use_div: true,
              thumb_path: image_item.thumb_url,
              original_size_path: image_item.original_size_url,
              url_for_downloading: image_item.download_url,
              no_mobile_overlay: true)
      .col-lg-6.col-sm-5.itemBoxRight{ style: 'height: 264px;' }
        %h4.name= image_item.name
        %p.brand= image_item.brand
        %p.dimensions= image_item.dimensions
        %p.price= image_item.price
        - if image_item.link_href.present?
          = link_to 'SHOP NOW', image_item.link_href,
            target: '_blank',
            class: "#{ tracked_link } link",
            data: { name: 'Final design - product item link' }
        .clearfix

app/views/clients/client_center/entries/_final_product_list.html.haml
- if product_items.present?
  .hLine10
  - product_items.each do |product_item|
    - unless product_item.image_id.nil?
      = render 'clients/client_center/entries/design_item', { image_item: ImageItemView.new(product_item) }
  .row.bottom60
    .col-md-12.disablePadding.text-right.product-list-pagination
      = will_paginate(product_items, container: false, renderer: ProductListPaginationRenderer)
- else
  .row.bottom60

app/views/clients/client_center/entries/_finished.html.haml
:coffee
  $ ->
    DesignerFinishedContestRequestPage.init()

- content_for :head do
  :javascript
    pageI18n = #{ translations_to_json(['client_center', 'finished']) }

  = javascript_include_tag 'contest_requests/finished_concept_board'

%h2.newSpaceReady
  = t('client_center.entries.space.congratulations')
  %span
  = t('client_center.entries.space.new_space_ready')
.ccFinalPage
  = render partial: 'clients/client_center/entries/phases',
            locals: { stripe: contest_page.entries_concept_board_page.phases_stripe }
  .row.designerDetail
    .col-sm-2.text-center
      = image_tag '/assets/profile-img1.png', width: 90, height: 90, class: 'img-circle'
    .col-sm-10
      %h4.centerXS= request.designer.name
      %p= request.final_note
      %h4= t('client_center.entries.space.share')
      .row.shareLook.social-share-button
        - SocialShareButton.config.allow_sites.each do |site|
          .col-xs-4{ share_button_parent_data(request, contest_page.share_url) }
            = render partial: 'clients/client_center/entries/share_button', locals: { site: site }

  .row.finalMoodboard
    .col-sm-12
      = render partial: 'clients/client_center/entries/final_design',
                locals: { request: request }
  .row
    .col-sm-12
      = link_to t('client_center.finished.download_images'),
          'javascript:void(0)',
          class: "downloadFinalMoodboard download-all #{ tracked_link }",
          data: { name: 'Final design - download' }

  .row.moodboardInstructions
    .col-sm-12
      - if request.pull_together_note.present?
        %h4= t('client_center.entries.space.pull_together')
        %p= request.pull_together_note
  - if contest_page.visible_image_items.present?
    %h4= t('client_center.entries.space.complete_lock')
    .fullWidthLine.marginBottom40.marginTop20

    :coffee
      $ ->
        ImageItemsPagination.init $('.ccFinalPage .imageItems')

    .imageItems{ data: { scope: 'image_items', url: "/contests/#{ contest_page.contest.id }/image_items" } }
      = render contest_page.entries_concept_board_page.image_items_partial

  .fullWidthLine.marginBottom40.marginTop20
  .row
    .col-sm-12.finalNote
      .titleRow
        .col-xs-12.col-sm-9
          %span.header= t('client_center.finished.final_note.title')
        .col-xs-12.col-sm-3
          %span.commentsCount= t('client_center.entries.finished.final_note.comments_count',
          count: @entries_page.entries_concept_board_page.final_notes.length)
        .col-xs-12.comments
          = render 'shared/request_comments_read_only',
            comments: @entries_page.entries_concept_board_page.final_notes
      = form_tag final_note_index_path, remote: true, id: 'final-note-to-designer' do
        = hidden_field_tag 'contest_request_id', request.id
        %textarea{ placeholder: t('client_center.finished.final_note.placeholder'),
                   name: 'final_note[text]' }
        %button.send-button= t('client_center.finished.final_note.button')

  - if @entries_page.entries_concept_board_page.show_contest_creation_button?
    .fullWidthLine.marginTop40
    .row
      .col-sm-12.startNewContest
        = link_to t('contests.index.new_contest'),
            new_contest_path,
            class: "create-contest-button #{ tracked_link }"

app/views/clients/client_center/entries/_more_features.html.haml
.more-features
  %h3.exploreMore= t('client_center.entries.more_features.title')
  .text-center.circleLinks
    %a{ href: Settings.external_urls.blog.get_ideas, class: tracked_link }
      %span= t('client_center.entries.more_features.get_inspired')
    %a{ href: Settings.external_urls.blog.client_stories, class: tracked_link }
      %span= t('client_center.entries.more_features.see_example')
    %a{ href: Settings.external_urls.blog.design_styles, class: tracked_link }
      %span= t('client_center.entries.more_features.styles_explained').html_safe
    .clearfix

app/views/clients/client_center/entries/_notes.html.haml
- if !(readonly && notes.blank?)
  .row.designerFeedback
    - if readonly
      .col-sm-12
        = render 'clients/client_center/entries/notes_list_container', notes: notes
    - else
      .col-sm-6
        = form_for ContestNote.new, remote: true do |f|
          = f.hidden_field :contest_id, value: @contest.id
          %h4= t('client_center.entries.notes_title')
          = f.text_area :text
          = f.submit t('client_center.entries.send_note'), class: 'btn'
      .col-sm-6
        = render 'clients/client_center/entries/notes_list_container', notes: notes

app/views/clients/client_center/entries/_notes_list.html.haml
- notes.each do |note|
  %li{ class: note.author_role }
    %p
      = note.name
    = note.text
    %p
      %span= note.ago_text
  %li.delimiter

app/views/clients/client_center/entries/_notes_list_container.html.haml
%h4= t('client_center.entries.your_note')
#scrollbox4.notes.client-notes-list
  %ul
    .template
      %li
        %p.note-text
          %span.time-ago
      %li.delimiter
    = render 'clients/client_center/entries/notes_list', notes: notes

app/views/clients/client_center/entries/_phases.html.haml
.moodboard-steps.steps123{ class: "#{ stripe.container_css_class } #{css_class if defined?(css_class)}" }
  - PhasesStripe::PHASES.each_with_index do |phase_name, index|
    %div{ class: stripe.css_class(index) }
      %span.number= index + 1
      %p.name= stripe.text(index)
  .clearfix

app/views/clients/client_center/entries/_responses_filter.html.haml
.responses-filter-dropdown.sortBySelect
  = form_tag client_center_entry_path(id: contest_id),
      id: 'responses-filter-form',
      method: 'get' do
    = hidden_field_tag 'answer', ''
    = hidden_field_tag 'view', view
    = hidden_mixpanel_submit_tag
  %select.selectpicker.form-selector.sortBySelect
    %option{ disabled: "disabled" }= t('client_center.entries.filter_by')
    - responses_filter_options.each do |answer, name|
      - attributes = { value: answer }
      - attributes[:selected] = 'selected' if answer == selected_answer
      %option{ attributes }= name

app/views/clients/client_center/entries/_winner.html.haml
.container.animated.fadeInDown.bottom60
  .row
    .col-md-12.disablePadding
      %h3.congrats
        = t('client_center.entries.congratulations')
        %span= t('client_center.entries.customized_board')
      .col-md-8.disablePadding
        = render partial: 'clients/client_center/entries/phases', locals: {active_tab: 2}
      %br/
      %br/
    .col-md-8.disablePadding.relative
      = image_tag '/assets/winnerBadge.png', class: 'winnerBadge'
      = render partial: 'shared/moodboard', locals: { request: @contest_requests[0] }
    .col-md-4
      = render partial: 'contest_requests/submission_info', locals: { designer: @contest_requests[0].designer, submitted_at: @contest_requests[0].created_at, request: @contest_requests[0] }